[*]
n-gpu-layers = -1
ctx-size = 0
ctx-checkpoints = 32
keep = -1
#load-mode = mlock
mmap = false
mlock = true
prio = 3
context-shift = false
no-kv-offload = false
no-warmup = true
kv-unified = true
batch-size = 512
ubatch-size = 64
cont-batching = true
n-predict = -1
flash-attn = true
log-verbosity = 3
parallel = 8
sleep-idle-seconds = -1
cache-type-k = q8_0
cache-type-v = q8_0
threads = 16
threads-batch = 8
# rope-freq-base = 1750000
# rope-freq-scale = 0.5
swa-full = false
cache-prompt = true
cache-ram = -1
cache-reuse = 4096
swa-checkpoints = 512
lookup-cache-static = /llama.cpp/lookup_cache_static.bin
lookup-cache-dynamic = /llama.cpp/lookup_cache_dynamic.bin
jinja = true
reasoning = true
reasoning-format = auto
reasoning-budget = 2048
reasoning-budget-message = "\n\n[Thinking budget reached. Answer directly:]\n\n"
spec-type = none

temp = 0.8                        # 0.8 - 1.0 prevents deterministic loops in thinking mode
top-p = 0.95
min-p = 0.05
top-k = 20                        # Lower top-k keeps candidate tokens focused
repeat-penalty = 1.05             # Subtle penalty to break phrasing loops
presence-penalty = 0.5            # Encourages new topic/token generation
frequency-penalty = 0.1
repeat-last-n = 256

[embeddinggemma-300M-Q8_0]
batch-size = 8192
ubatch-size = 8192

[NVIDIA-Nemotron-3-Super-120B-A12B-UD-Q4_K_XL-00001-of-00003]
ctx-size = 1048576

[NVIDIA-Nemotron-3-Super-120B-A12B-Q4_0_ROCMFP4]
ctx-size = 1048576

[NVIDIA-Nemotron-3.5-Lightning-30B-A3B-BF16]
ctx-size = 1048576

[NVIDIA-Nemotron-3.5-Lightning-30B-A3B-Q8_0]
ctx-size = 1048576

[NVIDIA-Nemotron-3.5-Lightning-30B-A3B-ROCMFP4]
ctx-size = 1048576

[Qwen3.6-35B-A3B-ROCMFP4]
ctx-size = 262144

[Qwen3.6-35B-A3B-Q8_0]
ctx-size = 262144

[Qwen3.6-35B-A3B-Q8_0-NOJINJA]
ctx-size = 262144
jinja = false

[Qwen3.6-35B-A3B-BF16]
ctx-size = 262144

[Qwen3.8-27B-BF16]
ctx-size = 262144

[Qwen3.8-27B-Q8_0]
ctx-size = 262144

[Qwen3-0.6B-Q8_0]
ctx-size = 262144

[Qwen3.8-Flash-Next-Q4_0_ROCMFP4_STRIX_LEAN]
ctx-size = 131072
spec-draft-n-max = 6
spec-draft-p-min = 0.6
spec-type = none
parallel = 2
mmap = true     # PLE Table comes from file through page cache
fit = off
jinja = true
